image: alpine:latest

pages:
  stage: deploy
  script:
  - apk add npm nodejs python3
  - npm install
  - WEBPACK_PUBLIC_PATH="public" npm run build-prod
  artifacts:
    paths:
    - dist
  only:
  - master
